server:
  port: 8080

spring:
  application:
    name: farseer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/farseer?serverTimezone=UTC
    username: 'howieyoung'
    password: '123456'
  redis:
    host: localhost
    port: 6379
    timeout: 30000

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
